version: '2'

services:
  drone-server:
    environment:
      DRONE_OPEN: "true"
      DRONE_HOST: http://127.0.0.1
      DRONE_SECRET: pizza
      DRONE_GOGS: "true"
      DRONE_GOGS_URL: "http://gogs:3000"
    image: drone/drone:latest
    restart: always
    ports:
      - 80:8000
      - 9000
    volumes:
      - drone-server-data:/var/lib/drone/

  drone-agent:
    command: agent
    environment:
      DRONE_SERVER: drone-server:9000
      DRONE_SECRET: pizza
    image: drone/agent:latest
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gogs
    image: postgres:9.5
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  gogs:
    environment:
      RUN_CROND: "true"
    image: gogs/gogs:latest
    restart: always
    ports:
      - "10022:22"
      - "3000:3000"
    volumes:
      - gogs-data:/data
    depends_on:
      - postgres

volumes:
  drone-server-data:
  db-data:
  gogs-data: